# Generated by Django 2.1.7 on 2019-05-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('cityen', models.CharField(db_column='cityEn', max_length=32)),
                ('cityzh', models.CharField(db_column='cityZh', max_length=32)),
                ('provinceen', models.CharField(db_column='provinceEn', max_length=32)),
                ('provincezh', models.CharField(db_column='provinceZh', max_length=32)),
                ('countryen', models.CharField(db_column='countryEn', max_length=32)),
                ('countryzh', models.CharField(db_column='countryZh', max_length=32)),
                ('leaderen', models.CharField(db_column='leaderEn', max_length=32)),
                ('leaderzh', models.CharField(db_column='leaderZh', max_length=32)),
                ('lat', models.CharField(max_length=32)),
                ('lon', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlacePm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('aqi', models.IntegerField()),
                ('area', models.CharField(max_length=12)),
                ('co', models.FloatField()),
                ('no2', models.FloatField()),
                ('o3', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pm2_5', models.FloatField()),
                ('position_name', models.CharField(max_length=24)),
                ('so2', models.FloatField()),
                ('time_point', models.DateTimeField()),
            ],
            options={
                'db_table': 'place_PM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlacePm2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('aqi', models.IntegerField()),
                ('area', models.CharField(max_length=12)),
                ('co', models.FloatField()),
                ('co_24h', models.FloatField()),
                ('no2', models.FloatField()),
                ('no2_24h', models.FloatField()),
                ('o3', models.FloatField()),
                ('o3_24h', models.FloatField()),
                ('o3_8h', models.FloatField()),
                ('o3_8h_24h', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pm10_24h', models.FloatField()),
                ('pm2_5', models.FloatField()),
                ('pm2_5_24h', models.FloatField()),
                ('position_name', models.CharField(max_length=24)),
                ('primary_pollutant', models.CharField(max_length=256)),
                ('quality', models.CharField(max_length=5)),
                ('so2', models.FloatField()),
                ('so2_24h', models.FloatField()),
                ('station_code', models.CharField(max_length=12)),
                ('time_point', models.DateTimeField()),
            ],
            options={
                'db_table': 'place_PM2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlacePmCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('coordinates', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'place_PM_coordinates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=10)),
                ('updatetime', models.DateTimeField()),
                ('day', models.DateTimeField()),
                ('week', models.CharField(max_length=8)),
                ('wea', models.CharField(max_length=6)),
                ('tem', models.IntegerField()),
                ('win', models.CharField(max_length=6)),
                ('win_speed', models.CharField(max_length=8)),
                ('win_meter', models.CharField(max_length=12)),
                ('humidity', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('air', models.IntegerField()),
                ('air_pm25', models.IntegerField()),
                ('air_level', models.CharField(max_length=6)),
                ('air_tips', models.TextField()),
                ('alarm', models.TextField()),
                ('cityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm25.City')),
            ],
        ),
    ]
